services:
  # Development service
  app:
    build:
      context: .
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules

  # Production Nginx with SSL
  app_prod:
    build:
      context: .
      target: prod
    ports:
      - "80:80"
      - "443:443"  # Expose HTTPS
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro  
      - ./certbot/conf/:/etc/letsencrypt/:ro             
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw                
